import { DataGrid, GridColDef } from "@mui/x-data-grid";

const columns: GridColDef[] = [
  { field: "id", headerName: "ID", width: 70, align: "center" },
  { field: "productName", headerName: "Nombre del producto", align: "center" },
  {
    field: "codBarra",
    headerName: "Codigo de barras",
    type: "number",
    align: "center",
  },
  {
    field: "precio",
    headerName: "Precio",
    type: "number",
    align: "center",
  },
];

const rows = [
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 1, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 2, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 3, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 4, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 5, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 6, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 7, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 8, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 9, productName: "Roxie", codBarra: 65, precio: 65 },
  { id: 10, productName: "Snow", codBarra: 35, precio: 35 },
  { id: 11, productName: "Lannister", codBarra: 42, precio: 42 },
  { id: 12, productName: "Lannister", codBarra: 45, precio: 45 },
  { id: 13, productName: "Stark", codBarra: 16, precio: 16 },
  { id: 14, productName: "Targaryen", codBarra: null, precio: 150 },
  { id: 15, productName: "Melisandre", codBarra: 150, precio: 150 },
  { id: 16, productName: "Clifford", codBarra: 44, precio: 44 },
  { id: 17, productName: "Frances", codBarra: 36, precio: 36 },
  { id: 18, productName: "Roxie", codBarra: 65, precio: 65 },
];

export default function TablaStock() {
  return (
    <div style={{ height: "70vh", width: "100%" }}>
      <DataGrid
        rows={rows}
        columns={columns}
        density="compact"
        style={{
          borderRadius: "10px",
          boxShadow: "0px 0px 10px 0px rgba(0,0,0,0.75)",
          padding: "10px",
        }}
      />
    </div>
  );
}
